#!/bin/sh
pactl=$(command -v pactl)
if [ -x "$pactl" ]; then
    pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo
fi

xset=$(command -v xset)
if [ -x "$xset" ]; then
    $xset -dpms
    $xset s off
fi
