#!/usr/bin/python
import sys, os

modes = {
    'off': 'xset -dpms;xset s off',
}

def print_help():
    print "Use: %s [%s]" % (sys.argv[0], ' | '.join(sorted(modes.keys())))

try:
    mode = sys.argv[1]
    os.system(modes[mode])
except IndexError:
    print_help()


