#!/usr/bin/python
import sys, os

internal = 'LVDS1'
external = 'VGA1'

def auto():
    return 'xrandr --auto'

def off():
    return 'xrandr --output VGA1 --off'

def dual(pos='above'):
    cmd = 'xrandr --output VGA1 --%s LVDS1' % pos
    return cmd

def clone():
    return 'xrandr --output VGA1 --same-as LVDS1'

modes = {
    'auto': auto,
    'clone': clone,
    'dual': dual,
    'off': off
}

def print_help():
    print "Use: %s [%s]" % (sys.argv[0], ' | '.join(sorted(modes.keys())))

try:
    mode = sys.argv[1:]
    if len(mode) == 1:
        cmd = modes[mode[0]]()
    else:
        cmd = modes[mode[0]](*mode[1:])

    os.system(cmd)

except IndexError:
    print_help()
