#!/bin/sh
pactl=$(command -v pactl)
if [ -x "$pactl" ]; then
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
fi

xset=$(command -v xset)
if [ -x "$xset" ]; then
    $xset +dpms
    $xset s on
fi
